### ISSUE TITLE
OpenELEC 3.0.0

### ISSUE THREAD

**Issue by frenzeldk** [vially/googlemusic-xbmc#22]
Getting this error when trying to run the plugin in the following version:
1. script.module.mutagen-1.21.0.zip
2. script.module.gmusicapi-2013.02.28.zip
3. plugin.audio.googlemusic-0.8.2.zip
on OpenELEC 3.0.0
"script failed: plugin.audio.googlemusic"
I installed them in the appropriate order and entered my credentials (application password bc. two-factor-authentication.

**Comment by vially** [comment]
I think it has to do with two-factor-authentication as mentioned by another user in issue #21.
Anyway, unless you provide the logs it will be hard to find the exact cause of your issues because the "script failed" message is just a generic error which pops up when there is an error in the python script.

Unfortunately I'm very busy at the moment with my day job so I can't look into it but I'll gladly accept a pull request.

Please post [your log file](http://wiki.xbmc.org/index.php?title=Log_file/Easy) here and maybe someone else can take a look into your issue and find a solution.

Cheers,
Valentin

**Comment by frenzeldk** [comment]
Sorry for my late response.
I did disable tow-factor-authentication afterwards and i did nothing differently. I will post logs ASAP.
